# Generated by Django 5.2.9 on 2025-12-04 09:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payout_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID заявки')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cумма к выплаты', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма выплаты')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли (RUB)'), ('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)'), ('CNY', 'Юани (CNY)')], default='RUB', help_text='Выберите тип валюты', verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждена'), ('processing', 'В обработке'), ('completed', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', verbose_name='Статус заявки')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Банк')),
                ('bank_bik', models.CharField(blank=True, help_text='Банковский идентификационный код', max_length=9, verbose_name='БИК банка')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='Номер карты')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Номер счёта')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон получателя')),
                ('description', models.TextField(blank=True, help_text='Основание для выплаты, назначение платежа', verbose_name='Описание / Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'currency'], name='payouts_pay_status_e314c4_idx'), models.Index(fields=['created_at'], name='payouts_pay_created_b65d12_idx')],
            },
        ),
    ]
