# Generated by Django 5.2.9 on 2025-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_bik',
            field=models.CharField(help_text='Банковский идентификационный код', max_length=9, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Банк'),
        ),
    ]
