# Generated by Django 5.2.9 on 2025-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_payout_account_number_alter_payout_bank_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('bank', 'Банковский перевод'), ('card', 'Перевод на карту')], default=1, help_text='Выберите способ выплаты', verbose_name='Способ выплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payout',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_bik',
            field=models.CharField(blank=True, help_text='Банковский идентификационный код', max_length=9, verbose_name='БИК банка'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['method'], name='payouts_pay_method_b7c103_idx'),
        ),
    ]
