# Generated by Django 5.2.9 on 2025-12-05 04:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_payout_method_alter_payout_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU'),
        ),
    ]
