# Generated by Django 5.2.9 on 2025-12-05 04:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_alter_payout_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Телефон для связи по выплате', max_length=128, region=None, verbose_name='Контактный телефон'),
        ),
    ]
